// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// exp_moving_avg
NumericVector exp_moving_avg(NumericVector x, double decay, int min_size);
RcppExport SEXP _yuez_exp_moving_avg(SEXP xSEXP, SEXP decaySEXP, SEXP min_sizeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< double >::type decay(decaySEXP);
    Rcpp::traits::input_parameter< int >::type min_size(min_sizeSEXP);
    rcpp_result_gen = Rcpp::wrap(exp_moving_avg(x, decay, min_size));
    return rcpp_result_gen;
END_RCPP
}
// ffill
NumericVector ffill(NumericVector x, int w);
RcppExport SEXP _yuez_ffill(SEXP xSEXP, SEXP wSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< int >::type w(wSEXP);
    rcpp_result_gen = Rcpp::wrap(ffill(x, w));
    return rcpp_result_gen;
END_RCPP
}
// first_true
int first_true(LogicalVector x);
RcppExport SEXP _yuez_first_true(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< LogicalVector >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(first_true(x));
    return rcpp_result_gen;
END_RCPP
}
// last_true
int last_true(LogicalVector x);
RcppExport SEXP _yuez_last_true(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< LogicalVector >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(last_true(x));
    return rcpp_result_gen;
END_RCPP
}
// running_min
NumericVector running_min(NumericVector x, int w, size_t min_size);
RcppExport SEXP _yuez_running_min(SEXP xSEXP, SEXP wSEXP, SEXP min_sizeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< int >::type w(wSEXP);
    Rcpp::traits::input_parameter< size_t >::type min_size(min_sizeSEXP);
    rcpp_result_gen = Rcpp::wrap(running_min(x, w, min_size));
    return rcpp_result_gen;
END_RCPP
}
// running_max
NumericVector running_max(NumericVector x, int w, size_t min_size);
RcppExport SEXP _yuez_running_max(SEXP xSEXP, SEXP wSEXP, SEXP min_sizeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< int >::type w(wSEXP);
    Rcpp::traits::input_parameter< size_t >::type min_size(min_sizeSEXP);
    rcpp_result_gen = Rcpp::wrap(running_max(x, w, min_size));
    return rcpp_result_gen;
END_RCPP
}
// running_mean
NumericVector running_mean(NumericVector x, int w, int min_size);
RcppExport SEXP _yuez_running_mean(SEXP xSEXP, SEXP wSEXP, SEXP min_sizeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< int >::type w(wSEXP);
    Rcpp::traits::input_parameter< int >::type min_size(min_sizeSEXP);
    rcpp_result_gen = Rcpp::wrap(running_mean(x, w, min_size));
    return rcpp_result_gen;
END_RCPP
}
// running_sd
NumericVector running_sd(NumericVector x, int w, int min_size);
RcppExport SEXP _yuez_running_sd(SEXP xSEXP, SEXP wSEXP, SEXP min_sizeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< int >::type w(wSEXP);
    Rcpp::traits::input_parameter< int >::type min_size(min_sizeSEXP);
    rcpp_result_gen = Rcpp::wrap(running_sd(x, w, min_size));
    return rcpp_result_gen;
END_RCPP
}
// running_sd0
NumericVector running_sd0(NumericVector x, int w, int min_size);
RcppExport SEXP _yuez_running_sd0(SEXP xSEXP, SEXP wSEXP, SEXP min_sizeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< int >::type w(wSEXP);
    Rcpp::traits::input_parameter< int >::type min_size(min_sizeSEXP);
    rcpp_result_gen = Rcpp::wrap(running_sd0(x, w, min_size));
    return rcpp_result_gen;
END_RCPP
}
// running_sum
NumericVector running_sum(NumericVector x, int w, int min_size);
RcppExport SEXP _yuez_running_sum(SEXP xSEXP, SEXP wSEXP, SEXP min_sizeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< int >::type w(wSEXP);
    Rcpp::traits::input_parameter< int >::type min_size(min_sizeSEXP);
    rcpp_result_gen = Rcpp::wrap(running_sum(x, w, min_size));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_yuez_exp_moving_avg", (DL_FUNC) &_yuez_exp_moving_avg, 3},
    {"_yuez_ffill", (DL_FUNC) &_yuez_ffill, 2},
    {"_yuez_first_true", (DL_FUNC) &_yuez_first_true, 1},
    {"_yuez_last_true", (DL_FUNC) &_yuez_last_true, 1},
    {"_yuez_running_min", (DL_FUNC) &_yuez_running_min, 3},
    {"_yuez_running_max", (DL_FUNC) &_yuez_running_max, 3},
    {"_yuez_running_mean", (DL_FUNC) &_yuez_running_mean, 3},
    {"_yuez_running_sd", (DL_FUNC) &_yuez_running_sd, 3},
    {"_yuez_running_sd0", (DL_FUNC) &_yuez_running_sd0, 3},
    {"_yuez_running_sum", (DL_FUNC) &_yuez_running_sum, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_yuez(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
